import {
  andValidator,
  anyOfValidator,
  colorValidator,
  dateValidator,
  emailValidator,
  maxValidator,
  minValidator,
  numberValidator,
  orValidator,
  passwordValidator,
  patternValidator,
  phoneValidator,
  requiredValidator,
  sameAsValidator,
  slugValidator,
  typeofValidator,
  uniqueValidator,
  urlValidator,
} from '.';

export const defaultValidators = {
  and: andValidator(),
  anyOf: anyOfValidator(),
  color: colorValidator(),
  date: dateValidator(),
  email: emailValidator(),
  max: maxValidator(),
  min: minValidator(),
  number: numberValidator(),
  or: orValidator(),
  password: passwordValidator(),
  pattern: patternValidator(),
  phone: phoneValidator(),
  required: requiredValidator(),
  sameAs: sameAsValidator(),
  slug: slugValidator(),
  typeof: typeofValidator(),
  unique: uniqueValidator(),
  url: urlValidator(),
};
