import { MargaritaFormControl } from '../margarita-form-control';
import {
  andValidator,
  anyOfValidator,
  caseValidator,
  colorValidator,
  controlNameCaseValidator,
  dateValidator,
  emailValidator,
  eaqualsToValidator,
  maxValidator,
  minValidator,
  numberValidator,
  integerValidator,
  floatValidator,
  positiveNumberValidator,
  negativeNumberValidator,
  orValidator,
  passwordValidator,
  patternValidator,
  phoneValidator,
  requiredValidator,
  sameAsValidator,
  slugValidator,
  typeofValidator,
  uniqueValidator,
  urlValidator,
  yupValidator,
  zodValidator,
} from '.';

const allValidators = {
  and: andValidator(),
  anyOf: anyOfValidator(),
  case: caseValidator(),
  color: colorValidator(),
  date: dateValidator(),
  email: emailValidator(),
  eaqualsTo: eaqualsToValidator(),
  max: maxValidator(),
  min: minValidator(),
  controlNameCase: controlNameCaseValidator(),
  number: numberValidator(),
  integer: integerValidator(),
  float: floatValidator(),
  positiveNumber: positiveNumberValidator(),
  negativeNumber: negativeNumberValidator(),
  or: orValidator(),
  password: passwordValidator(),
  pattern: patternValidator(),
  phone: phoneValidator(),
  tel: phoneValidator(),
  required: requiredValidator(),
  sameAs: sameAsValidator(),
  slug: slugValidator(),
  typeof: typeofValidator(),
  unique: uniqueValidator(),
  url: urlValidator(),
  yup: yupValidator(),
  zod: zodValidator(),
};

Object.entries(allValidators).forEach(([name, validator]) => {
  MargaritaFormControl.addValidator(name, validator);
});
